version: "3.9"

services:

  production-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: c'est le mot de pass de la base 2 données
      POSTGRES_DB: ytdpnl
    ports:
      - 54321:5432
    volumes:
      - production-ytdpnl:/var/lib/postgresql/data

  development-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: c'est le mot de pass de la base 2 données pour le dev
      POSTGRES_DB: ytdpnl
    ports:
      - 54322:5432
    volumes:
      - development-ytdpnl:/var/lib/postgresql/data

volumes:

  production-ytdpnl:
    driver: local

  development-ytdpnl:
    driver: local
